version: "3.8"

services:
    web:
        build: .
        command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - ./project:/app  # ربط مجلد المشروع
            - ./project/media:/app/media
            - ./project/project/static:/app/static
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=project.settings

    nginx:
        image: nginx:latest
        volumes:
            - ./project:/app
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - web
